version: "3.8"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - DOTNET_ENVIRONMENT=Development
    command: ["dotnet", "test", "SAFER.Tests/SAFER.Tests.csproj"]